## Import Data

In [ ]:
import kagglehub
import pandas as pd
import sqlite3
import os

path = kagglehub.dataset_download("rauffauzanrambe/fifa-world-cup-2026-player-performance-dataset")

project_dir = r"xxxxxxxxxxxxxxxxxxxx"
db_path = os.path.join(project_dir, "data_analyst.db")
conn = sqlite3.connect(db_path)

print("Mulai memasukkan tabel ke SQLite...")
for file in os.listdir(path):
    if file.endswith('.csv'):
        table_name = os.path.splitext(file)[0]

        csv_full_path = os.path.join(path, file)
        df_temp = pd.read_csv(csv_full_path)

        df_temp.to_sql(table_name, conn, if_exists='replace', index=False)
        print(f"-> Tabel '{table_name}' berhasil dibuat. Ukuran: {df_temp.shape}")

cursor = conn.cursor()
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
print("\nDaftar tabel resmi di database kamu:", cursor.fetchall())

conn.close()

c:\Users\dicky\AppData\Local\Programs\Python\Python313\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Downloading to C:\Users\dicky\.cache\kagglehub\datasets\rauffauzanrambe\fifa-world-cup-2026-player-performance-dataset\1.archive...

100%|██████████| 3.96M/3.96M [00:01<00:00, 2.46MB/s]

Extracting files...

Mulai memasukkan tabel ke SQLite...
-> Tabel 'fifa_world_cup_2026_player_performance' berhasil dibuat. Ukuran: (54600, 75)

Daftar tabel resmi di database kamu: [('fifa_world_cup_2026_player_performance',)]

In [2]:
conn = sqlite3.connect(db_path)

df_wc = pd.read_sql_query("SELECT * FROM fifa_world_cup_2026_player_performance", conn)

## Data Cleaning

In [3]:
df_wc.head(10)

,player_id,player_name,age,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot,...,possession_impact,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating
0,P00055,Rodri Fati,26,Spanish,Spain,3,Goalkeeper,195,75,Left,...,1.1,44.2,55.9,42.0,51.8,0,0,242,0,5.8
1,P00070,Ansu Le Normand,19,Spanish,Spain,18,Midfielder,178,75,Right,...,3.5,38.2,43.7,31.1,52.7,0,3,342,0,5.5
2,P00066,Gavi Ramos,18,Spanish,Spain,14,Midfielder,177,72,Left,...,15.3,99.0,99.0,83.4,54.8,1,1,245,0,8.4
3,P00073,Pedro Cubarsi,20,Spanish,Spain,21,Forward,182,74,Right,...,1.2,19.8,42.3,40.9,78.5,5,3,422,0,6.7
4,P00059,Alvaro Oyarzabal,23,Spanish,Spain,7,Defender,191,81,Left,...,6.2,44.1,33.5,60.0,56.6,0,0,440,0,5.7
5,P00072,Dani Gavi,21,Spanish,Spain,20,Midfielder,181,78,Right,...,17.0,65.4,85.8,91.1,48.2,1,2,332,0,6.7
6,P00058,Rodri Laporte,27,Spanish,Spain,6,Defender,188,80,Right,...,6.4,48.7,15.3,61.8,55.1,0,1,264,0,7.0
7,P00078,Ansu Fati,27,Spanish,Spain,26,Forward,182,72,Right,...,2.4,48.2,35.6,60.9,60.4,2,1,191,0,6.8
8,P00056,Pedro Torres,24,Spanish,Spain,4,Defender,176,78,Left,...,6.4,52.7,31.3,68.3,59.2,0,0,324,0,6.7
9,P00074,Gavi Le Normand,25,Spanish,Spain,22,Forward,172,70,Right,...,11.1,99.0,68.8,92.1,47.6,1,3,547,0,5.7

In [4]:
df_wc.describe()

,age,jersey_number,height_cm,weight_kg,market_value_eur,goals_team,goals_opponent,minutes_played,goals,assists,...,possession_impact,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating
count,54600.000000,54600.000000,54600.000000,54600.000000,5.460000e+04,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,...,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000
mean,26.296484,13.500000,181.654341,75.754853,2.008445e+07,1.330476,1.330476,36.199817,0.055385,0.052363,...,2.850165,60.318379,46.135778,63.750396,55.572154,0.643993,0.607601,272.300311,0.030659,3.634046
std,4.067519,7.500069,6.277792,3.951481,2.718866e+07,1.147814,1.147814,36.419755,0.251900,0.239021,...,4.228436,20.234988,22.424337,19.860028,13.661343,1.093781,0.931527,116.806184,0.206520,3.163411
min,17.000000,1.000000,163.000000,65.000000,5.288220e+05,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,15.000000,5.000000,25.000000,15.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,23.000000,7.000000,177.000000,73.000000,4.444778e+06,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,43.700000,29.800000,46.500000,46.400000,0.000000,0.000000,184.000000,0.000000,0.000000
50%,26.000000,13.500000,182.000000,76.000000,1.027111e+07,1.000000,1.000000,24.000000,0.000000,0.000000,...,1.100000,57.000000,40.500000,61.100000,55.000000,0.000000,0.000000,268.000000,0.000000,5.400000
75%,29.000000,20.000000,186.000000,78.000000,2.342013e+07,2.000000,2.000000,75.000000,0.000000,0.000000,...,4.000000,75.100000,59.000000,78.900000,63.900000,1.000000,1.000000,359.000000,0.000000,6.400000
max,39.000000,26.000000,200.000000,87.000000,2.000000e+08,7.000000,7.000000,90.000000,4.000000,3.000000,...,37.000000,99.000000,99.000000,99.000000,99.000000,10.000000,8.000000,615.000000,4.000000,9.500000

In [5]:
df_wc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54600 entries, 0 to 54599
Data columns (total 75 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   player_id                 54600 non-null  object
 1   player_name               54600 non-null  object
 2   age                       54600 non-null  int64
 3   nationality               54600 non-null  object
 4   team                      54600 non-null  object
 5   jersey_number             54600 non-null  int64
 6   position                  54600 non-null  object
 7   height_cm                 54600 non-null  int64
 8   weight_kg                 54600 non-null  int64
 9   preferred_foot            54600 non-null  object
 10  club_name                 54600 non-null  object
 11  market_value_eur          54600 non-null  int64
 12  match_id                  54600 non-null  object
 13  match_date                54600 non-null  object
 14  stadium                   54600 non-null  object
 15  city                      54600 non-null  object
 16  opponent_team             54600 non-null  object
 17  tournament_stage          54600 non-null  object
 18  match_result              54600 non-null  object
 19  goals_team                54600 non-null  int64
 20  goals_opponent            54600 non-null  int64
 21  minutes_played            54600 non-null  int64
 22  goals                     54600 non-null  int64
 23  assists                   54600 non-null  int64
 24  shots                     54600 non-null  int64
 25  shots_on_target           54600 non-null  int64
 26  expected_goals_xg         54600 non-null  float64
 27  expected_assists_xa       54600 non-null  float64
 28  key_passes                54600 non-null  int64
 29  successful_passes         54600 non-null  int64
 30  total_passes              54600 non-null  int64
 31  pass_accuracy             54600 non-null  float64
 32  dribbles_attempted        54600 non-null  int64
 33  successful_dribbles       54600 non-null  int64
 34  crosses                   54600 non-null  int64
 35  successful_crosses        54600 non-null  int64
 36  tackles                   54600 non-null  int64
 37  interceptions             54600 non-null  int64
 38  clearances                54600 non-null  int64
 39  blocks                    54600 non-null  int64
 40  aerial_duels_won          54600 non-null  int64
 41  aerial_duels_lost         54600 non-null  int64
 42  recoveries                54600 non-null  int64
 43  defensive_actions         54600 non-null  int64
 44  fouls_committed           54600 non-null  int64
 45  fouls_suffered            54600 non-null  int64
 46  yellow_cards              54600 non-null  int64
 47  red_cards                 54600 non-null  int64
 48  offsides                  54600 non-null  int64
 49  saves                     54600 non-null  int64
 50  save_percentage           54600 non-null  float64
 51  punches                   54600 non-null  int64
 52  clean_sheet               54600 non-null  int64
 53  goals_conceded            54600 non-null  int64
 54  penalty_saves             54600 non-null  int64
 55  distance_covered_km       54600 non-null  float64
 56  sprint_distance_km        54600 non-null  float64
 57  top_speed_kmh             54600 non-null  float64
 58  accelerations             54600 non-null  int64
 59  decelerations             54600 non-null  int64
 60  stamina_score             54600 non-null  float64
 61  player_rating             54600 non-null  float64
 62  performance_score         54600 non-null  float64
 63  offensive_contribution    54600 non-null  float64
 64  defensive_contribution    54600 non-null  float64
 65  possession_impact         54600 non-null  float64
 66  pressure_resistance       54600 non-null  float64
 67  creativity_score          54600 non-null  float64
 68  consistency_score         54600 non-null  float64
 69  clutch_performance_score  54600 non-null  float64
 70  total_goals_tournament    54600 non-null  int64
 71  total_assists_tournament  54600 non-null  int64
 72  total_minutes_tournament  54600 non-null  int64
 73  player_of_match_awards    54600 non-null  int64
 74  tournament_rating         54600 non-null  float64
dtypes: float64(18), int64(43), object(14)
memory usage: 31.2+ MB

In [10]:
duplicate_count = df_wc.duplicated().sum()
print(f"Jumlah baris Duplikat : {duplicate_count}")

logical_duplicates = df_wc.duplicated(subset=['player_id', 'match_id']).sum()
print(f"Jumlah duplikasi logis (player_id + match_id): {logical_duplicates}")

Jumlah baris Duplikat : 0
Jumlah duplikasi logis (player_id + match_id): 0

In [13]:
df_wc['match_date'] = pd.to_datetime(df_wc['match_date'], errors='coerce')

invalid_dates = df_wc['match_date'].isna().sum()
print(f"Jumlah tanggal tidak valid: {invalid_dates}")

print(f"Tanggal pertandingan pertama: {df_wc['match_date'].min()}")
print(f"Tanggal pertandingan terakhir: {df_wc['match_date'].max()}")

Jumlah tanggal tidak valid: 0
Tanggal pertandingan pertama: 2026-06-11 00:00:00
Tanggal pertandingan terakhir: 2026-07-31 00:00:00

In [21]:
df_wc['minutes_played'].describe()

count    54600.000000
mean        36.199817
std         36.419755
min          0.000000
25%          0.000000
50%         24.000000
75%         75.000000
max         90.000000
Name: minutes_played, dtype: float64

In [27]:
shots_anomaly = (df_wc['shots_on_target'] > df_wc['shots']).sum()
print(f"Jumlah baris error (Shots on Target > Total Shots): {shots_anomaly}")

passes_anomaly = (df_wc["successful_passes"] > df_wc["total_passes"]).sum()
print(f"Jumlah baris error (Successful passes > total passes): {passes_anomaly}")

Jumlah baris error (Shots on Target > Total Shots): 0
Jumlah baris error (Successful passes > total passes): 0

In [35]:
menit_aktual = df_wc.groupby('player_id')['minutes_played'].sum().reset_index(name='calculated_minutes')

menit_tercatat = df_wc.groupby('player_id')['total_minutes_tournament'].first().reset_index()

merge_check = menit_aktual.merge(menit_tercatat, on='player_id')
mismatch_minutes = merge_check[merge_check['calculated_minutes'] != merge_check['total_minutes_tournament']]

print(f"Jumlah pemain dengan total menit turnamen tidak sinkron: {len(mismatch_minutes)}")

mismatch_minutes['selisih'] = mismatch_minutes['calculated_minutes'] - mismatch_minutes['total_minutes_tournament']
print(mismatch_minutes.head())

match_counts = df_wc[df_wc['player_id'].isin(mismatch_minutes['player_id'])].groupby('player_id').size().reset_index(name='jumlah_match')
print(match_counts.head())

print("\nStatistik jumlah pertandingan per pemain secara keseluruhan:")
print(df_wc.groupby('player_id').size().describe())

print(df_wc[df_wc['player_id'] == 'P00001'][['player_name', 'team', 'opponent_team', 'tournament_stage', 'minutes_played', 'match_date']].head(10))

Jumlah pemain dengan total menit turnamen tidak sinkron: 1248
  player_id  calculated_minutes  total_minutes_tournament  selisih
0    P00001                 953                       348      605
1    P00002                 830                       329      501
2    P00003                 922                        87      835
3    P00004                1299                       208     1091
4    P00005                1298                       143     1155
  player_id  jumlah_match
0    P00001            34
1    P00002            34
2    P00003            34
3    P00004            34
4    P00005            34

Statistik jumlah pertandingan per pemain secara keseluruhan:
count    1248.000000
mean       43.750000
std         7.033999
min        33.000000
25%        38.000000
50%        44.000000
75%        47.250000
max        66.000000
dtype: float64
            player_name    team opponent_team tournament_stage  \
1246   Kylian Griezmann  France     Australia      Group Stage
4626   Kylian Griezmann  France         Spain      Group Stage
9176   Kylian Griezmann  France        Canada      Group Stage
9827   Kylian Griezmann  France     Australia      Group Stage
10790  Kylian Griezmann  France       Belgium      Group Stage
11492  Kylian Griezmann  France        Canada      Group Stage
12790  Kylian Griezmann  France   South Korea      Group Stage
14012  Kylian Griezmann  France  South Africa      Group Stage
14974  Kylian Griezmann  France         Ghana      Group Stage
15366  Kylian Griezmann  France      Scotland      Group Stage

       minutes_played match_date
1246                0 2026-07-24
4626                0 2026-07-02
9176                0 2026-07-12
9827                0 2026-07-14
10790              81 2026-07-17
11492              61 2026-07-09
12790               0 2026-07-23
14012               0 2026-06-20
14974               0 2026-07-10
15366              50 2026-07-17

In [37]:
df_wc['total_minutes_tournament'] = df_wc.groupby('player_id')['minutes_played'].transform('sum')
df_wc['total_goals_tournament'] = df_wc.groupby('player_id')['goals'].transform('sum')
df_wc['total_assists_tournament'] = df_wc.groupby('player_id')['assists'].transform('sum')

mismatch_check = df_wc[df_wc.groupby('player_id')['minutes_played'].transform('sum') != df_wc['total_minutes_tournament']]
print(f"Jumlah pemain tidak sinkron setelah diperbaiki: {len(mismatch_check)}")

Jumlah pemain tidak sinkron setelah diperbaiki: 0

In [39]:
string_cols = df_wc.select_dtypes(include=['object']).columns
for col in string_cols:
    df_wc[col] = df_wc[col].astype(str).str.strip()

print("Daftar Posisi Pemain:")
print(df_wc['position'].unique())

print("\nDaftar Kaki Dominan:")
print(df_wc['preferred_foot'].unique())

print("\nDaftar Fase Turnamen:")
print(df_wc['tournament_stage'].unique())

Daftar Posisi Pemain:
['Goalkeeper' 'Midfielder' 'Forward' 'Defender']

Daftar Kaki Dominan:
['Left' 'Right']

Daftar Fase Turnamen:
['Group Stage' 'Round of 32' 'Round of 16' 'Quarter Finals' 'Semi Finals'
 'Third Place Match' 'Final']

In [41]:
print("Statistik Akurasi Umpan:")
print(df_wc['pass_accuracy'].describe()[['min', 'max']])

print("\nStatistik Persentase Penyelamatan Kiper:")
print(df_wc['save_percentage'].describe()[['min', 'max']])

Statistik Akurasi Umpan:
min    0.42
max    0.97
Name: pass_accuracy, dtype: float64

Statistik Persentase Penyelamatan Kiper:
min    0.0
max    1.0
Name: save_percentage, dtype: float64

In [43]:
bukan_kiper_save = df_wc[(df_wc['position'] != 'Goalkeeper') & (df_wc['save_percentage'] > 0)]
print(f"Jumlah pemain non-kiper yang punya skor save percentage: {len(bukan_kiper_save)}")

kiper_nol_save = df_wc[(df_wc['position'] == 'Goalkeeper') & (df_wc['save_percentage'] == 0.0)]
print(f"Jumlah match di mana kiper asli memiliki save percentage 0.0: {len(kiper_nol_save)}")

Jumlah pemain non-kiper yang punya skor save percentage: 0
Jumlah match di mana kiper asli memiliki save percentage 0.0: 4295

## Exploratory Data Analysis

In [45]:
# 1. Statistik deskriptif untuk umur, tinggi, dan berat badan
print("Distribusi Fisik Pemain")
print(df_wc[['age', 'height_cm', 'weight_kg']].describe())

# 2. Sebaran persentase penggunaan kaki dominan
print("\nSebaran Kaki Dominan")
print(df_wc['preferred_foot'].value_counts(normalize=True) * 100)

# 3. Jumlah pemain unik berdasarkan posisi
# (Menggunakan drop_duplicates agar satu pemain hanya dihitung sekali)
print("\nJumlah Pemain Unik per Posisi")
print(df_wc.drop_duplicates(subset=['player_id'])['position'].value_counts())

Distribusi Fisik Pemain
                age     height_cm     weight_kg
count  54600.000000  54600.000000  54600.000000
mean      26.296484    181.654341     75.754853
std        4.067519      6.277792      3.951481
min       17.000000    163.000000     65.000000
25%       23.000000    177.000000     73.000000
50%       26.000000    182.000000     76.000000
75%       29.000000    186.000000     78.000000
max       39.000000    200.000000     87.000000

Sebaran Kaki Dominan
preferred_foot
Right    74.461538
Left     25.538462
Name: proportion, dtype: float64

Jumlah Pemain Unik per Posisi
position
Defender      432
Midfielder    384
Forward       288
Goalkeeper    144
Name: count, dtype: int64

In [49]:
ofensif_posisi = df_wc.groupby('position')[['goals', 'assists', 'shots', 'expected_goals_xg']].mean()
print("Rata-rata Statistik Ofensif per Match berdasarkan Posisi")
print(ofensif_posisi)

Rata-rata Statistik Ofensif per Match berdasarkan Posisi
               goals   assists     shots  expected_goals_xg
position
Defender    0.018677  0.023915  0.216614           0.002094
Forward     0.143254  0.078333  0.984444           0.047054
Goalkeeper  0.000000  0.008254  0.000000           0.000000
Midfielder  0.051548  0.081429  0.470893           0.014718

In [50]:
disiplin_posisi = df_wc.groupby('position')[['fouls_committed', 'yellow_cards', 'red_cards']].mean()
print("=== Rata-rata Statistik Disiplin per Match berdasarkan Posisi ===")
print(disiplin_posisi)

=== Rata-rata Statistik Disiplin per Match berdasarkan Posisi ===
            fouls_committed  yellow_cards  red_cards
position
Defender           0.429471      0.124180   0.006085
Forward            0.436667      0.085476   0.005476
Goalkeeper         0.274444      0.083968   0.005397
Midfielder         0.441310      0.082917   0.005238

In [52]:
df_pemain_unik = df_wc.drop_duplicates(subset=['player_id'])

top_scorers = df_pemain_unik[['player_name', 'team', 'position', 'total_goals_tournament']].sort_values(by='total_goals_tournament', ascending=False).head(5)

top_assisters = df_pemain_unik[['player_name', 'team', 'position', 'total_assists_tournament']].sort_values(by='total_assists_tournament', ascending=False).head(5)

print("TOP 5 SCORERS TOURNEY")
print(top_scorers.to_string(index=False))

print("\nTOP 5 ASSISTERS TOURNEY")
print(top_assisters.to_string(index=False))

TOP 5 SCORERS TOURNEY
     player_name        team position  total_goals_tournament
Memphis Zerrouki Netherlands  Forward                      24
    Kasey Hector     Jamaica  Forward                      16
Dominik Kramaric     Croatia  Forward                      15
  Eric Rodriguez      Panama  Forward                      15
 Mohannad Majeed        Iraq  Forward                      15

TOP 5 ASSISTERS TOURNEY
        player_name          team   position  total_assists_tournament
   Yassine El Yamiq       Morocco Midfielder                        13
     Anibal Sanchez        Panama    Forward                        12
Moumi Choupo-Moting      Cameroon Midfielder                        11
        Mehdi Arefi          Iran Midfielder                        10
   Giovanni Tillman United States Midfielder                        10

In [54]:
korelasi_rating = df_wc[['player_rating', 'goals', 'assists', 'shots_on_target', 
                         'pass_accuracy', 'defensive_actions', 'distance_covered_km']].corr()['player_rating']

print("Korelasi Metrik terhadap Player Rating")
print(korelasi_rating.sort_values(ascending=False))

Korelasi Metrik terhadap Player Rating
player_rating          1.000000
distance_covered_km    0.837282
defensive_actions      0.564601
goals                  0.217196
assists                0.204418
shots_on_target        0.185107
pass_accuracy          0.074662
Name: player_rating, dtype: float64

## Ekspor Data

In [55]:
df_wc.to_csv('piala_dunia_2026_clean.csv', index=False)
print("Data berhasil diexport menjadi 'piala_dunia_2026_clean.csv'!")

Data berhasil diexport menjadi 'piala_dunia_2026_clean.csv'!